# Generated by Django 4.0.4 on 2022-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
