# Generated by Django 4.0.4 on 2022-04-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drink',
            name='pub_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pubs', to='pubs.pub'),
            preserve_default=False,
        ),
    ]
