# Generated by Django 4.0.4 on 2022-04-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_price_drink_pub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='pub_id',
            new_name='pub',
        ),
    ]
