# Generated by Django 4.0.4 on 2022-04-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pubs', '0001_initial'),
        ('drinks', '0002_drink_price_drink_pub_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='drinks.drink')),
                ('pub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pubs.pub')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='users.user')),
            ],
        ),
    ]
