# Generated by Django 4.0.4 on 2022-04-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drinks', '__first__'),
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='drinks.drink')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pubs.pub')),
            ],
        ),
    ]
