# Generated by Django 4.0.4 on 2022-04-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='pub_id',
            new_name='pub',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
    ]
