# Generated by Django 4.0.4 on 2022-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('amount', models.PositiveSmallIntegerField(null=True)),
                ('send_date', models.DateField(null=True)),
            ],
        ),
    ]
