# Generated by Django 4.0.4 on 2022-04-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recd_transfers', to='users.user'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='users.user'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='send_date',
            field=models.DateField(null=True),
        ),
    ]
